apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: thiolengkiat413/product-service
    newTag: staging-1

replicas:
  - name: product-service
    count: 2

patches:
  - path: service-nodeport-patch.yaml
    target:
      kind: Service
      name: product-service
  - path: ingress-host-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: product-service
